language: node_js
node_js:
  - stable
notifications:
  email: "false"
before_script:
  - sls create -t spotinst-nodejs -p ../test
  - npm link && cd ../test && npm link serverless-spotinst-functions
  - npm i serverless -s
  - serverless config credentials -p spotinst -t ${token} -a ${account}
  - cd ../serverless-spotinst-functions
script:
  - npm test
